### ISSUE TITLE
Week 4 Review Ticket - Alex Do

### ISSUE THREAD

**Issue by AlexD017** [willcyber/tri3#36]
# Score: 5/5 Graded by: Nathan Manangan
Link to Individual Github Page: [here](https://alexd017.github.io/Tri3-IndivRepo/)
### CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
- [x] CB Create Task Coding requirements documented
- [x] Runtime of Code(with comments) on Replit/Intellij

### Accounts and Logins Challenges/Hacks (3 Points - Pair/Trio)

- [x] Hack#1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack#2 Add logout to CRUD screen
- [x] Hack#3 Add login_required to another portion of the project
- [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by ProRichyMan** [comment]
Score 5/5

Link To Github Page: [Link](https://alexd017.github.io/Tri3-IndivRepo/task)

Create Task
- [x] Create Task Coding requirements documented
- [x] Runtime of Code

Accounts and Logins
- [x] Hack #1 Add Phone Number to Sign Up / Authorization screen
- [x] Hack #2 Add logout to CRUD screen
- [x] Hack #3 Add login_required to another portion of the project

Extra Credit
- [ ] A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
